### ISSUE TITLE
Extension version not found

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#13]
I started to get this error yesterday:

```
$ chromexup -v
[DEBUG] found 1 configuration file(s): ['/home/ren/.config/chromexup/config.ini']
[INFO] config.ini, processing 1 extension(s)
[DEBUG] Starting new HTTPS connection (1): clients2.google.com:443
[DEBUG] https://clients2.google.com:443 "GET /service/update2/crx?response=redirect&prodversion=199&acceptformat=crx2,crx3&x=id%3Dcjpalhdlnbpafiamejdnhcphjbkeiagm%26installsource%3Dondemand%26uc HTTP/1.1" 302 None
[ERROR] extension version not found
[DEBUG] https://clients2.googleusercontent.com/crx/blobs/Acy1k0YbWUzdtO9XsX05qikx6LtzwKWitrph8jtfnCwZBMaLGOpkjh8DY4J9w8U6dBnUr3UKo6LdSiZeGYRAn5V5X60Qzpam8defKBbvq4lYy7rgfvDqWwDGUprlhTE0HsxkPA2Y5N5ErsySnsd1BFo/CJPALHDLNBPAFIAMEJDNHCPHJBKEIAGM_1_52_2_0.crx
Traceback (most recent call last):
  File "/usr/bin/chromexup", line 33, in <module>
    sys.exit(load_entry_point('chromexup==0.5.1', 'console_scripts', 'chromexup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/chromexup/main.py", line 342, in main
    pool.map(process, extensions)
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/chromexup/main.py", line 49, in process
    (latest_ver, url) = _get_latest_version(id)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/chromexup/main.py", line 113, in _get_latest_version
    raise RuntimeError
RuntimeError
```

**Comment by xsmile** [comment]
Hi, thanks for the hint.

The URL where the extension version is parsed from was changed. I pushed an update.
