### ISSUE TITLE
Error when extension is deleted in webstore

### ISSUE THREAD

**Issue by rEnr3n** [xsmile/chromexup#4]
I have this extension installed and now it's gone - error 404. https://chrome.google.com/webstore/detail/olffebgbihkemhnlpeficnplfoiabljj

```
Traceback (most recent call last):
  File "/usr/bin/chromexup", line 11, in <module>
    load_entry_point('chromexup==0.4.1', 'console_scripts', 'chromexup')()
  File "/usr/lib/python3.6/site-packages/chromexup/main.py", line 327, in main
    pool.map(process, extensions)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/lib/python3.6/site-packages/chromexup/main.py", line 49, in process
    (latest_ver, url) = _get_latest_version(id)
  File "/usr/lib/python3.6/site-packages/chromexup/main.py", line 101, in _get_latest_version
    url = r.next.url
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by xsmile** [comment]
Version 0.4.3 should fix this. A warning is printed if such an extension is found but the script will continue to run.
